# Di dalam container
sudo ./install.sh
sudo ./install.sh
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh
sudo ./install.sh
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh
sudo ./install.sh
sudo ./install.sh
ls -al
cd /var/www/html
ls -al
php -v
rm -rf index.html
sudo rm -rf index.html
ls -al
cd ~
ls -al
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
cat /var/log/dashboard_install_20250723_171317.log
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
sudo ./uninstall.sh 
sudo ./install.sh 
exit
