# ==============================================================================
#   Docker Compose untuk Lingkungan Tes Dashboard Server
# ==============================================================================

version: "3.8"

services:
  dashboard-test-env:
    build:
      context: .
      dockerfile: Dockerfile

    image: debian-dashboard-test:latest
    container_name: dashboard-test-container
    privileged: true
    ports:
      - "8080:80"

    # PERUBAHAN DI SINI: Tambahkan 'volumes'
    # Ini akan me-mount seluruh folder proyek saat ini (.)
    # ke dalam direktori /home/tester di dalam container.
    volumes:
      - .:/home/tester/

    stdin_open: true
    tty: true
